import { PropertyDetails } from "@/types/types";

export const initialPropertyDetails: PropertyDetails = {
  general_details: {
    price: "",
    taxes: "",
    address: "",
    lot_size: "",
    directions: "",
  },
  room_interior: {
    rooms: 0,
    rooms_plus: 0,
    bedrooms: 0,
    bedrooms_plus: 0,
    kitchens: 0,
    family_room: "",
    basement: "",
  },
  exterior: {
    property_type: "",
    style: "",
    exterior: "",
    garage_type: "",
    drive_parking_spaces: 0,
    pool: "",
  },
  utilities: {
    fireplace_stove: "",
    heat_source: "",
    heat_type: "",
    central_air_conditioning: "",
    laundry_level: "",
    sewers: "",
    water: "",
  },
  at_a_glance: {
    type: "",
    area: "",
    municipality: "",
    neighborhood: "",
    style: "",
    lot_size: "",
    tax: "",
    beds: 0,
    baths: 0,
    fireplace: "",
    pool: "",
  },
  _id: "",
  name: "",
  category: "",
  available_for: "",
  listing_id: "",
  property_description: "",
  image_urls: [],
  street_view: "",
  map_location: "",
  latitude: "",
  longitude: "",
  pincode: "",
  country: "",
  state: "",
  city: "",
  square_feet: 0,
};
